method: bayes
metric:
  goal: maximize
  name: Eval Images Metrics Dict (all images)/psnr
parameters:
  pipeline.datamanager.dataparser.scale_factor:
    distribution: q_log_uniform
    max: 10.0
    min: 0.1
    q: 0.1
  pipeline.model.distortion_loss_mult:
    distribution: q_log_uniform
    max: 0.01
    min: 0.0004
    q: 0.0002
  pipeline.model.disable_scene_contraction:
    values: [True, False]
  optimizers.fields.optimizer.lr:
    distribution: q_log_uniform
    max: 0.1
    min: 0.001
    q: 0.001
  optimizers.fields.scheduler.lr_final:
    distribution: q_log_uniform
    max: 0.001
    min: 0.00001
    q: 0.00001
command:
  - ${env}
  - ns-train
  - nerfacto
  - --vis wandb
  - --project_name radiance-field-qa
  - --experiment_name lego
  - --viewer.quit_on_train_completion True
  - ${args}
  - blender-data
  - --data ~/Datasets/NeRF/blender/lego