method: grid
project: radiance-field-qa
metric:
  goal: maximize
  name: Eval Images Metrics Dict (all images)/combined_score
parameters:
  # pipeline.model.proposal_net_args_list.0.hidden_dim:
  #   values: [16]
  # pipeline.model.proposal_net_args_list.0.log2_hashmap_size:
  #   values: [16]
#  pipeline.model.log2_hashmap_size:
#    values: [14, 15, 16, 17]
  pipeline.model.num_levels:
    values: [64] #[8, 16, 32, 64]
  pipeline.model.features_per_level:
    values: [2, 4]
  pipeline.model.log2_hashmap_total_size:
    values: [24, 20, 23, 21, 22]
  # pipeline.model.hidden_dim:
  #   values: [64]
  # pipeline.model.hidden_dim_color:
  #   values: [64]
  # pipeline.model.proposal_net_args_list.0.num_levels:
  #   values: [5]
  # pipeline.model.proposal_net_args_list.0.max_res:
  #   values: [128]
  # optimizers.fields.optimizer.lr:
  #   values: [0.006, 0.009]
  # optimizers.proposal_networks.optimizer.lr:
  #   values: [0.006]
  a_scene:
    values:
      - drums
      - lego
      - hotdog
command:
  - ${env}
  - python
  - wandb/train.py
  - ${args}