method: bayes
project: radiance-field-qa
metric:
  goal: maximize
  name: Eval Images Metrics Dict (all images)/combined_score
parameters:
  pipeline.model.proposal_net_args_list.0.hidden_dim:
    values: [8, 16]
  pipeline.model.proposal_net_args_list.0.log2_hashmap_size:
    values: [15, 16, 17]
  pipeline.model.log2_hashmap_size:
    values: [16, 17, 18, 19]
  pipeline.model.hidden_dim:
    values: [64, 128]
  pipeline.model.hidden_dim_color:
    values: [64, 128]
  pipeline.model.proposal_net_args_list.0.num_levels:
    values: [4,5,6]
  pipeline.model.proposal_net_args_list.0.max_res:
    values: [128,256]
  optimizers.fields.optimizer.lr:
    values: [0.003, 0.006, 0.009]
  optimizers.proposal_networks.optimizer.lr:
    values: [0.02, 0.01, 0.005]
  # data:
  #   values:
  #     - ~/Datasets/NeRF/blender/lego
  #     - ~/Datasets/NeRF/blender/hotdog
  #     - ~/Datasets/NeRF/blender/drums
command:
  - ${env}
  - bash
  - wandb/train_arg_parser_grid.sh
  - ${args}