method: grid
project: radiance-field-qa
metric:
  goal: maximize
  name: Eval Images Metrics Dict (all images)/psnr
parameters:
  pipeline.model.proposal_net_args_list.0.hidden_dim:
    values: [8, 16, 32, 64]
  pipeline.model.proposal_net_args_list.0.log2_hashmap_size:
    values: [15, 16, 17, 18, 19]
command:
  - ${env}
  - bash
  - wandb/train_arg_parser_grid.sh
  - ${args}