method: bayes
metric:
  goal: maximize
  name: Eval Images Metrics Dict (all images)/psnr
parameters:
  scale-factor:
    distribution: q_log_uniform_values
    q: 0.1
    max: 10.0
    min: 0.1
  pipeline.model.distortion_loss_mult:
    distribution: q_log_uniform_values
    q: 0.0002
    max: 0.01
    min: 0.0004
  pipeline.model.disable_scene_contraction:
    values: [True, False]
  optimizers.fields.optimizer.lr:
    distribution: q_log_uniform_values
    q: 0.001
    max: 0.1
    min: 0.001
  optimizers.fields.scheduler.lr_final:
    distribution: q_log_uniform_values
    q: 0.00001
    max: 0.001
    min: 0.00001
command:
  - ${env}
  - bash
  - wandb/train_arg_parser.sh
  - ${args}