method: bayes
project: radiance-field-qa
metric:
  goal: maximize
  name: Eval Images Metrics Dict (all images)/combined_score
parameters:
  # pipeline.model.proposal_net_args_list.0.hidden_dim:
  #   values: [16]
  pipeline.model.proposal_net_args_list.0.log2_hashmap_size:
    values: [15, 16, 17]
  pipeline.model.proposal_net_args_list.1.log2_hashmap_size:
    values: [15, 16, 17]
  pipeline.model.num_levels:
    values: [32] #, 16, 8]
  pipeline.model.features_per_level:
    values: [2] #, 4, 8]
  pipeline.model.log2_hashmap_total_size:
    values: [24] #, 20, 23, 21, 22]
  pipeline.model.interlevel_loss_mult:
    values: [1.0, 1.1, 0.9]
  pipeline.model.distortion_loss_mult:
    values: [0.003, 0.002, 0.005]
  # pipeline.model.hidden_dim:
  #   values: [64]
  # pipeline.model.hidden_dim_color:
  #   values: [64]
  # pipeline.model.proposal_net_args_list.0.num_levels:
  #   values: [5]
  # pipeline.model.proposal_net_args_list.0.max_res:
  #   values: [128]
  optimizers.fields.optimizer.lr:
    values: [0.01, 0.02, 0.005]
  optimizers.proposal_networks.optimizer.lr:
    values: [0.01, 0.02, 0.005]
  a_scene:
    values:
      - drums
      # - lego
      # - hotdog
command:
  - ${env}
  - python
  - wandb/train.py
  - ${args}